#!/usr/bin/env bash
sDir=$(cd `dirname $0`; pwd)
echo ${sDir}
sProjectDir=$(cd `dirname $(dirname ${sDir})`; pwd)

sHookDir=${sProjectDir}'/.git/hooks/'

if [ -d ${sHookDir} ]; then
	cd ${sProjectDir}
	vendor/bin/phpcs --config-set installed_paths vendor/fp-coding-standards/fpcs

	cd ${sHookDir}
	ln -sf ../../git-hooks/pre-commit .
	echo
	echo 'install success'
else
	echo
	echo ${sHookDir}' is not exist'
	exit 1
fi
