#!/usr/bin/env bash
sDir=$(cd `dirname $0`; pwd)
sProjectDir=$(cd `dirname ${sDir}`; pwd)
sHookDir=${sProjectDir}'/.git/hooks/'

if [ -d ${sHookDir} ]; then
	cd ${sProjectDir}

	if [ ! -d 'vendor/fp-coding-standards/fpcs' ]; then
		composer require fp-coding-standards/fpcs --dev
		vendor/bin/phpcs --config-set installed_paths vendor/fp-coding-standards/fpcs
	fi

	cd ${sHookDir}
	ln -sf ../../git-hooks/pre-commit .
	echo
	echo 'install success'
else
	echo
	echo ${sHookDir}' is not exist'
	exit 1
fi
