#!/usr/bin/env bash
sDir=$(cd `dirname $0`; pwd)
sHookDir=$(cd `dirname ${sDir}`; pwd)'/.git/hooks/'

if [ -d ${sHookDir} ]; then
	cd ${sDir}
	composer require fp-coding-standards/fpcs

	cd ${sHookDir}
	ln -sf ../../git_hook/pre-commit .
	echo 'done'
else
	echo ${sHookDir}' is not exist'
	exit 1
fi
