#!/usr/bin/env bash
sDir=$(cd `dirname $0`; pwd)
sProjectDir=$(cd `dirname ${sDir}`; pwd)
sHookDir=${sProjectDir}'/.git/hooks/'

if [ -d ${sHookDir} ]; then
	cd ${sProjectDir}
	composer require fp-coding-standards/fpcs --update-no-dev
	vendor/bin/phpcs --config-set installed_paths vendor/fp-coding-standards/fpcs

	cd ${sHookDir}
	ln -sf ../../git-hooks/pre-commit .
	echo
	echo 'install success'
else
	echo ${sHookDir}' is not exist'
	exit 1
fi
